In [1]:
import numpy as np
import json
with open("us-county-boundaries.json") as f:
  data = json.load(f)
coords = data[0]['fields']['geo_shape']["coordinates"][0]
arr = np.array(coords)
arr.shape

(7660, 2)

In [5]:
poly = list(arr)
poly

[array([-120.713744,   39.482788]),
 array([-120.713697,   39.482872]),
 array([-120.713675,   39.482921]),
 array([-120.713682,   39.483061]),
 array([-120.713782,   39.483216]),
 array([-120.714338,   39.483624]),
 array([-120.714453,   39.483693]),
 array([-120.714514,   39.483744]),
 array([-120.714568,   39.483835]),
 array([-120.714588,   39.483876]),
 array([-120.714644,   39.48399 ]),
 array([-120.714964,   39.484366]),
 array([-120.715002,   39.48443 ]),
 array([-120.715033,   39.484493]),
 array([-120.715048,   39.484566]),
 array([-120.715048,   39.484611]),
 array([-120.715155,   39.484824]),
 array([-120.715171,   39.485036]),
 array([-120.715155,   39.485176]),
 array([-120.715124,   39.485229]),
 array([-120.715071,   39.485363]),
 array([-120.715018,   39.485475]),
 array([-120.714964,   39.48569 ]),
 array([-120.714965,   39.48574 ]),
 array([-120.714949,   39.485798]),
 array([-120.714972,   39.485879]),
 array([-120.715048,   39.486021]),
 array([-120.715124,   39.48

In [11]:
from shapely.geometry import Point
from shapely.geometry.polygon import Polygon

point = Point(-120.7, 39.4)
polygon = Polygon(poly)
print(polygon.contains(point))

True
